# Generated by Django 6.0.4 on 2026-04-19 01:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, max_length=32, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=32)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('QR', 'VietQR')], default='COD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_verification', 'Awaiting verification'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('payment_screenshot', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('category', models.CharField(choices=[('Bouquet', 'Bouquet'), ('Single Stem', 'Single Stem'), ('Gift Set', 'Gift Set'), ('Custom', 'Custom')], default='Bouquet', max_length=30)),
                ('is_best_seller', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('images', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-is_best_seller', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='store.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('feedback', models.TextField()),
                ('avatar', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
