import { SiteCopy } from './types';

export const en: SiteCopy = {
  header: {
    brandName: 'Flourish',
    brandTagline: 'Handmade keepsakes',
    nav: {
      home: 'Home',
      products: 'Shop',
      cart: 'Cart',
    },
    adminAriaLabel: 'Open admin settings',
    cartAriaLabel: 'Open cart',
    logoAlt: 'Flourish logo',
  },
  footer: {
    description:
      'Handmade velvet wire flower bunches for graduations, birthdays, thank-you gifts, and every moment that deserves something lasting.',
    socialLinks: {
      instagram: 'Instagram',
      facebook: 'Facebook',
    },
    quickAccessTitle: 'Quick Access',
    connectTitle: 'Connect With Us',
    contact: {
      email: 'hello@flourish.vn',
      phone: '+84 123 456 789',
      location: 'Nha Trang, Vietnam',
    },
    bottomLine: 'Handmade keepsakes for moments worth holding onto.',
    bottomTagline: 'Designed for gifting, celebration, and thoughtful messages.',
  },
  home: {
    heroKicker: 'For everlasting memories',
    heroTitle: 'Flowers that never fade.',
    heroCopy:
      'Handmade velvet wire flowers designed to last beyond every special moment. Flourish creates warm, photo-ready bouquets for graduation, gifting, and celebrations that deserve something lasting.',
    ctaPrimary: 'Shop now',
    ctaSecondary: 'Handmade in Nha Trang',
    stats: [
      { value: '100%', label: 'Hand-shaped stems and bouquet wrapping' },
      { value: '7749', label: 'Ways to customize your bouquet as you wish' },
      { value: 'Lasting', label: 'A bouquet that stays with the memory, not just the moment' },
    ],
    signature: {
      kicker: 'Signature feeling',
      title: 'Soft textures, quiet luxury, and gift-ready details.',
      copy: 'Designed to feel delicate, polished, and meaningful from the first glance to the unwrapping moment.',
    },
    brandStory: {
      kicker: 'Brand story',
      title: 'A bouquet that keeps the feelings alive.',
      paragraphs: [
        'We believe that some moments deserve more than flowers that fade away.',
        'Each of our velvet wire flowers is carefully handcrafted to capture emotions that last, whether it is love, friendship, gratitude, or celebration.',
        'What started as a small idea between friends has grown into a way to make meaningful gifts more accessible, beautiful, and lasting.',
      ],
    },
    whyFlourish: {
      kicker: 'Why Flourish?',
      title: 'Consistent, thoughtful, gift-ready.',
      copy: '',
      features: [
        {
          title: 'Made to last',
          description: 'Each bunch is designed to stay beautiful well beyond the day you gift it.',
        },
        {
          title: 'Handmade with love',
          description: 'Every stem is shaped and wrapped by hand so the final bouquet feels personal.',
        },
        {
          title: 'Reliable gifting',
          description: 'Clean wrapping, clear checkout, and easy order confirmation for important moments.',
        },
      ],
    },
    occasions: {
      kicker: 'Perfect for',
      title: 'Bouquets for every meaningful occasion.',
      items: [
        {
          title: 'Graduation',
          description: 'Celebrate milestones with bouquets that look polished in photos.',
        },
        {
          title: 'Meaningful gifts',
          description: 'A thoughtful keepsake for friends, partners, teachers, and family.',
        },
        {
          title: 'Romantic moments',
          description: 'Soft textures and lasting colors for anniversaries and love notes.',
        },
      ],
    },
    reviews: {
      kicker: 'Customer feedback',
      title: 'Word from our customers',
      copy: '',
    },
  },
  products: {
    listing: {
      kicker: 'Product page',
      title: 'Handmade bunches for gifting, milestones, and everyday sweetness.',
      copy: '',
      bestSellersTitle: 'Best sellers',
      bestSellersCopy: 'The bouquets customers pick most often',
      allProductsTitle: 'All products',
      availableLabel: (count) => `${count} available`,
      emptyTitle: 'No products yet',
      emptyCopy: 'Add your first bouquets from the admin panel and they will appear here in the same card layout.',
      bestSellerPill: 'Best seller',
      popularPill: 'Popular',
      inCartLabel: (count) => `${count} in cart`,
    },
    detail: {
      backToShop: 'Back to shop',
      bestSellerPill: 'Best seller',
      inCartPill: (count) => `In cart: ${count}`,
      cards: [
        {
          title: 'Thoughtful gifting',
          description: 'Designed to look elegant for graduation, birthdays, thank-you gifts, and keepsakes.',
        },
        {
          title: 'Gift-ready finish',
          description: 'Clean bouquet wrapping, polished presentation, and details that feel premium in hand.',
        },
      ],
      addToCart: 'Add to cart',
      keepBrowsing: 'Keep browsing',
      galleryAlt: (productName, index) => `${productName} preview ${index + 1}`,
    },
  },
  cart: {
    empty: {
      title: 'Your cart is still empty.',
      copy: 'Start with a bouquet that matches the occasion, then come back here to confirm quantities and checkout.',
      cta: 'Browse products',
    },
    page: {
      kicker: 'Shopping cart',
      title: 'Review your bouquet selection.',
      copy: 'Adjust quantities, remove anything that no longer fits, and continue when the order feels right.',
      summaryTitle: 'Order summary',
      itemsLabel: 'Items',
      deliveryLabel: 'Delivery confirmation',
      deliveryValue: 'At checkout',
      paymentLabel: 'Payment methods',
      paymentValue: 'COD / VietQR',
      totalLabel: 'Total',
      checkoutCta: 'Proceed to checkout',
      continueCta: 'Continue shopping',
    },
  },
  checkout: {
    empty: {
      title: 'There is nothing to check out yet.',
      copy: 'Add a bouquet to your cart first, then come back here to complete delivery and payment details.',
      cta: 'Browse products',
    },
    page: {
      kicker: 'Checkout',
      title: 'Confirm delivery details and choose how you want to pay.',
      copy: 'Keep the form simple, make the payment choice clear, and show proof-upload only when it is actually needed.',
      deliveryTitle: 'Delivery information',
      fields: {
        fullName: 'Full name *',
        phone: 'Phone number *',
        address: 'Delivery address *',
      },
      placeholders: {
        fullName: 'Nguyen Van A',
        phone: '09xx xxx xxx',
        address: 'Street, ward, district, city...',
      },
      paymentTitle: 'Payment method',
      codTitle: 'Cash on delivery',
      codCopy: 'Customer pays when the bouquet is delivered.',
      qrTitle: 'VietQR transfer',
      qrCopy: 'Customer transfers first, then uploads payment proof for admin review.',
      generateQr: 'Generate transfer details',
      generatingQr: 'Preparing transfer...',
      manualTransferLabel: 'Manual transfer',
      qrUnavailableTitle: 'QR unavailable',
      qrUnavailableCopy: 'Continue with the bank details on the right and upload your payment proof after transferring.',
      amountLabel: 'Amount to transfer',
      orderNumberLabel: 'Order number',
      paymentDescriptionLabel: 'Payment description',
      accountNumberLabel: 'Account number',
      accountNameLabel: 'Account name',
      bankBinLabel: 'Bank BIN',
      transferModeLabel: 'Transfer mode',
      transferModeLive: 'VietQR live',
      transferModeFallback: 'Manual fallback',
      uploadCopy: 'After completing the transfer, upload a screenshot below so the order can move into payment verification.',
      refreshQr: 'Refresh VietQR',
      retryQr: 'Retry VietQR',
      refreshingQr: 'Refreshing...',
      uploadLabel: 'Upload payment screenshot *',
      uploadTitle: 'Click to upload payment proof',
      uploadCopySecondary: 'JPG, PNG, or screenshot image from your banking app.',
      submit: 'Place order',
      summaryTitle: 'Order summary',
      quantityLabel: (count) => `Qty ${count}`,
      totalLabel: 'Total',
      reviewFlowTitle: 'Payment review flow',
      reviewFlowCopy: 'QR orders should move to awaiting verification after proof upload. COD orders can stay simple and proceed straight to confirmation.',
    },
    alerts: {
      nameRequiredForQr: 'Please enter your name before generating the transfer details.',
      requiredFields: 'Please fill in all required fields.',
      uploadScreenshot: 'Please upload your payment screenshot before placing the order.',
      generateTransferDetails: 'Please generate the transfer details before placing the order.',
      qrUnavailable: 'VietQR is temporarily unavailable. Use the manual transfer details below.',
      generateQrFailed: 'Failed to generate QR code.',
      paymentReferenceFallback: 'FLOURISH ORDER',
      generatingOrderNumber: 'Generating...',
    },
  },
  app: {
    addedToCart: (productName) => `${productName} has been added to your cart.`,
    placeOrderFailed: 'Failed to place order. Please try again.',
    deleteProductConfirm: 'Are you sure you want to delete this product?',
    addProductFailed: 'Failed to add product.',
    updateProductFailed: 'Failed to update product.',
    deleteProductFailed: 'Failed to delete product.',
    deleteOrderConfirm: (orderNumber) => `Are you sure you want to delete order ${orderNumber}?`,
    deleteOrderFailed: 'Failed to delete order.',
    updateOrderFailed: 'Failed to update order.',
    backendLoadingTitle: 'Loading storefront data',
    backendLoadingCopy: 'Connecting to the backend and preparing products, reviews, and checkout services.',
    loading: {
      placingOrderTitle: 'Confirming your order',
      placingOrderCopy: 'We are sending your order details to the backend and saving everything securely.',
      generatingQrTitle: 'Preparing transfer details',
      generatingQrCopy: 'We are generating your payment details and checking QR availability.',
      adminLoginTitle: 'Signing you in',
      adminLoginCopy: 'We are verifying your admin account and preparing the dashboard.',
      savingProductTitle: 'Saving product changes',
      savingProductCopy: 'We are updating the catalog and syncing the latest product data.',
      deletingProductTitle: 'Removing product',
      deletingProductCopy: 'We are deleting the product and refreshing the storefront inventory.',
      updatingOrderTitle: 'Updating order',
      updatingOrderCopy: 'We are saving the new order status and refreshing the admin queue.',
      deletingOrderTitle: 'Deleting order',
      deletingOrderCopy: 'We are removing the order and refreshing the latest records.',
    },
    adminLogin: {
      kicker: 'Private access',
      title: 'Admin sign in',
      copy: 'Keep the operational side separate, but styled with the same care as the storefront.',
      usernameLabel: 'Admin username',
      usernamePlaceholder: 'Admin username',
      passwordLabel: 'Admin password',
      passwordPlaceholder: 'Enter admin password',
      login: 'Login',
      cancel: 'Cancel',
      footnote: 'Use a real Django staff account',
    },
    orderSuccess: {
      kicker: 'Order confirmed',
      title: 'Your Flourish order has been placed.',
      copy: 'We received your request and will follow up with confirmation details. If you chose QR transfer, your payment proof will be reviewed in the admin queue.',
      homeCta: 'Back to home',
      productsCta: 'Continue shopping',
    },
  },
};
