import { SiteCopy } from './types';

export const vi: SiteCopy = {
  header: {
    brandName: 'Flourish',
    brandTagline: 'Quà tặng thủ công',
    nav: {
      home: 'Trang chủ',
      products: 'Cửa hàng',
      cart: 'Giỏ hàng',
    },
    adminAriaLabel: 'Mở cài đặt admin',
    cartAriaLabel: 'Mở giỏ hàng',
    languageToggleLabel: 'Đổi ngôn ngữ',
  },
  footer: {
    description:
      'Với những đóa hoa kẽm nhung được làm thủ công tỉ mỉ, Flourish giúp những dịp trọng đại trở nên càng đáng nhớ hơn.',
    socialLinks: {
      instagram: 'Instagram',
      facebook: 'Facebook',
    },
    quickAccessTitle: 'Truy cập nhanh',
    connectTitle: 'Liên hệ',
    contact: {
      email: 'hello@flourish.vn',
      phone: '+84 123 456 789',
      location: 'Thành phố Nha Trang, tỉnh Khánh Hòa, Việt Nam',
    },
    bottomLine: 'Kỷ niệm trong những đóa hoa.',
    bottomTagline: 'Phát triển bởi notmtri.',
  },
  home: {
    heroKicker: 'Kỷ niệm trong những đóa hoa',
    heroTitle: 'Những bông hoa không bao giờ tàn',
    heroCopy:
      '',
    ctaPrimary: 'Mua ngay',
    ctaSecondary: 'Được làm thủ công tại Nha Trang',
    stats: [
      { value: '100%', label: 'hoa được làm thủ công' },
      { value: '7749', label: 'cách để đa dạng hóa bó hoa của bạn' },
      { value: 'Mãi mãi', label: 'lưu giữ những kỉ niệm của bạn' },
    ],
    signature: {
      kicker: 'Cam giac dac trung',
      title: 'Mem mai, tinh te va san sang de tang.',
      copy: 'Moi chi tiet duoc tao de mang lai cam giac nhe nhang, chi chu va y nghia tu cai nhin dau tien den luc mo qua.',
    },
    brandStory: {
      kicker: 'Cau chuyen thuong hieu',
      title: 'Bo hoa giu lai cam xuc that lau.',
      paragraphs: [
        'Chung toi tin rang co nhung khoanh khac xung dang nhan duoc hon ca nhung bong hoa som phai mau.',
        'Moi bong hoa nhung uon day deu duoc lam thu cong can than de giu lai tinh cam lau ben, du do la tinh yeu, tinh ban, su biet on hay niem vui chung mung.',
        'Tu mot y tuong nho giua nhung nguoi ban, Flourish dan tro thanh cach de nhung mon qua y nghia tro nen de tiep can, dep hon va ben hon.',
      ],
    },
    whyFlourish: {
      kicker: 'Vi sao la Flourish',
      title: 'Dong deu, tinh te, san sang de tang.',
      copy: 'Trai nghiem can giu duoc su nhe nhang va chi chu tu luc xem san pham den khi thanh toan. Chung toi thiet ke website voi cung su can than do.',
      features: [
        {
          title: 'Ben dep lau',
          description: 'Moi bo hoa duoc tao ra de van dep that lau sau ngay duoc trao tang.',
        },
        {
          title: 'Lam thu cong co chu y',
          description: 'Moi canh va cach goi deu duoc lam bang tay de bo hoa cuoi cung cam thay that rieng tu.',
        },
        {
          title: 'Tang qua yen tam',
          description: 'Dong goi gon gang, dat hang ro rang va xac nhan de dang cho nhung dip quan trong.',
        },
      ],
    },
    occasions: {
      kicker: 'Phu hop cho',
      title: 'Bo hoa cho moi dip y nghia.',
      items: [
        {
          title: 'Tot nghiep',
          description: 'Danh dau cot moc bang nhung bo hoa len hinh dep va gon gang.',
        },
        {
          title: 'Qua tang y nghia',
          description: 'Mot mon qua de thuong cho ban be, nguoi thuong, thay co va gia dinh.',
        },
        {
          title: 'Khoanh khac lang man',
          description: 'Chat lieu mem va mau sac ben lau cho ky niem, ky niem ngay cuoi hay loi yeu thuong.',
        },
      ],
    },
    reviews: {
      kicker: 'Cam nhan khach hang',
      title: 'Mot dong loi khen chuyen dong lien tuc.',
      copy: 'Su tin tuong se thuyet phuc hon khi van giu duoc cam giac ca nhan. Cac the danh gia nay giu trang chu sinh dong ma khong qua roi.',
    },
  },
  products: {
    listing: {
      kicker: 'Trang san pham',
      title: 'Nhung bo hoa lam tay cho qua tang, cot moc va su ngot ngao moi ngay.',
      copy: 'Xem the san pham gon gang, nhieu goc chup va them vao gio voi cam giac yen tam hon.',
      bestSellersTitle: 'Ban chay',
      bestSellersCopy: 'Nhung bo hoa duoc khach chon nhieu nhat',
      allProductsTitle: 'Tat ca san pham',
      availableLabel: (count) => `${count} san pham`,
      emptyTitle: 'Chua co san pham',
      emptyCopy: 'Them bo hoa dau tien tu trang admin va san pham se hien thi tai day voi cung bo cuc the.',
      bestSellerPill: 'Ban chay',
      popularPill: 'Noi bat',
      inCartLabel: (count) => `${count} trong gio`,
    },
    detail: {
      backToShop: 'Quay lai cua hang',
      bestSellerPill: 'Ban chay',
      inCartPill: (count) => `Trong gio: ${count}`,
      cards: [
        {
          title: 'Tang qua chu dao',
          description: 'Phu hop cho le tot nghiep, sinh nhat, qua cam on va nhung mon qua de luu giu.',
        },
        {
          title: 'Hoan thien san sang de tang',
          description: 'Goi hoa gon gang, trinh bay tinh te va chi tiet tao cam giac cao cap khi cam tren tay.',
        },
      ],
      addToCart: 'Them vao gio',
      keepBrowsing: 'Xem tiep',
      galleryAlt: (productName, index) => `${productName} goc chup ${index + 1}`,
    },
  },
  cart: {
    empty: {
      title: 'Gio hang cua ban van trong.',
      copy: 'Hay bat dau voi mot bo hoa phu hop cho dip dac biet, sau do quay lai day de kiem tra so luong va thanh toan.',
      cta: 'Xem san pham',
    },
    page: {
      kicker: 'Gio hang',
      title: 'Xem lai lua chon bo hoa cua ban.',
      copy: 'Dieu chinh so luong, bo san pham khong con phu hop va tiep tuc khi don hang da vua y.',
      summaryTitle: 'Tom tat don hang',
      itemsLabel: 'San pham',
      deliveryLabel: 'Xac nhan giao hang',
      deliveryValue: 'Tai buoc thanh toan',
      paymentLabel: 'Phuong thuc thanh toan',
      paymentValue: 'COD / VietQR',
      totalLabel: 'Tong cong',
      checkoutCta: 'Tiep tuc thanh toan',
      continueCta: 'Tiep tuc mua sam',
    },
  },
  checkout: {
    empty: {
      title: 'Chua co gi de thanh toan.',
      copy: 'Hay them bo hoa vao gio truoc, sau do quay lai day de dien thong tin giao hang va thanh toan.',
      cta: 'Xem san pham',
    },
    page: {
      kicker: 'Thanh toan',
      title: 'Xac nhan thong tin giao hang va chon cach thanh toan.',
      copy: 'Giu form don gian, cach thanh toan ro rang va chi hien tai lenh tai anh khi that su can.',
      deliveryTitle: 'Thong tin giao hang',
      fields: {
        fullName: 'Ho va ten *',
        phone: 'So dien thoai *',
        address: 'Dia chi giao hang *',
      },
      placeholders: {
        fullName: 'Nguyen Van A',
        phone: '09xx xxx xxx',
        address: 'So nha, phuong, quan, thanh pho...',
      },
      paymentTitle: 'Phuong thuc thanh toan',
      codTitle: 'Thanh toan khi nhan hang',
      codCopy: 'Khach thanh toan khi bo hoa duoc giao den.',
      qrTitle: 'Chuyen khoan VietQR',
      qrCopy: 'Khach chuyen khoan truoc, sau do tai len anh xac nhan de admin kiem tra.',
      generateQr: 'Tao thong tin chuyen khoan',
      generatingQr: 'Dang chuan bi...',
      manualTransferLabel: 'Chuyen khoan thu cong',
      qrUnavailableTitle: 'QR tam thoi khong kha dung',
      qrUnavailableCopy: 'Hay dung thong tin ngan hang ben phai va tai len anh thanh toan sau khi chuyen.',
      amountLabel: 'So tien chuyen',
      orderNumberLabel: 'Ma don hang',
      paymentDescriptionLabel: 'Noi dung chuyen khoan',
      accountNumberLabel: 'So tai khoan',
      accountNameLabel: 'Ten tai khoan',
      bankBinLabel: 'Ma BIN ngan hang',
      transferModeLabel: 'Che do chuyen khoan',
      transferModeLive: 'VietQR dang hoat dong',
      transferModeFallback: 'Du phong thu cong',
      uploadCopy: 'Sau khi chuyen khoan xong, hay tai len anh xac nhan ben duoi de don hang duoc chuyen sang buoc kiem tra thanh toan.',
      refreshQr: 'Lam moi VietQR',
      retryQr: 'Thu lai VietQR',
      refreshingQr: 'Dang lam moi...',
      uploadLabel: 'Tai len anh thanh toan *',
      uploadTitle: 'Bam de tai len minh chung',
      uploadCopySecondary: 'Anh JPG, PNG hoac anh chup man hinh tu ung dung ngan hang.',
      submit: 'Dat hang',
      summaryTitle: 'Tom tat don hang',
      quantityLabel: (count) => `SL ${count}`,
      totalLabel: 'Tong cong',
      reviewFlowTitle: 'Luong kiem tra thanh toan',
      reviewFlowCopy: 'Don VietQR nen chuyen sang trang thai cho xac minh sau khi tai anh len. Don COD co the di thang den xac nhan.',
    },
    alerts: {
      nameRequiredForQr: 'Vui long nhap ten truoc khi tao thong tin chuyen khoan.',
      requiredFields: 'Vui long dien day du cac truong bat buoc.',
      uploadScreenshot: 'Vui long tai len anh thanh toan truoc khi dat hang.',
      generateTransferDetails: 'Vui long tao thong tin chuyen khoan truoc khi dat hang.',
      qrUnavailable: 'VietQR tam thoi khong kha dung. Hay dung thong tin chuyen khoan thu cong ben duoi.',
      generateQrFailed: 'Khong tao duoc ma QR.',
      paymentReferenceFallback: 'DON HANG FLOURISH',
      generatingOrderNumber: 'Dang tao...',
    },
  },
  app: {
    addedToCart: (productName) => `Da them ${productName} vao gio hang.`,
    placeOrderFailed: 'Dat hang that bai. Vui long thu lai.',
    deleteProductConfirm: 'Ban co chac muon xoa san pham nay khong?',
    addProductFailed: 'Them san pham that bai.',
    updateProductFailed: 'Cap nhat san pham that bai.',
    deleteProductFailed: 'Xoa san pham that bai.',
    updateOrderFailed: 'Cap nhat don hang that bai.',
    adminLogin: {
      kicker: 'Truy cap rieng',
      title: 'Dang nhap admin',
      copy: 'Giu phan van hanh tach biet, nhung van dong bo cam quan voi storefront.',
      usernameLabel: 'Ten dang nhap admin',
      usernamePlaceholder: 'Ten dang nhap admin',
      passwordLabel: 'Mat khau admin',
      passwordPlaceholder: 'Nhap mat khau admin',
      login: 'Dang nhap',
      cancel: 'Huy',
      footnote: 'Dung tai khoan staff Django that',
    },
    orderSuccess: {
      kicker: 'Da xac nhan don hang',
      title: 'Don hang Flourish cua ban da duoc tao.',
      copy: 'Chung toi da nhan yeu cau va se lien he lai voi thong tin xac nhan. Neu ban chon chuyen khoan QR, minh chung thanh toan se duoc admin kiem tra.',
      homeCta: 'Ve trang chu',
      productsCta: 'Tiep tuc mua sam',
    },
  },
};
